# Default values for trendradar.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: wantcat/trendradar
  pullPolicy: Always
  tag: "latest"

mcp:
  enabled: false
  image:
    repository: wantcat/trendradar-mcp
    pullPolicy: Always
    tag: "latest"

persistence:
  enabled: true
  storageClass: "local-storage-nvme"
  accessMode: ReadWriteOnce
  size: 5Gi

appService:
  type: NodePort
  port: 8080
  nodePort: 31082

mcpService:
  type: NodePort
  port: 3333
  nodePort: 31333

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

env:
  ENABLE_WEBSERVER: "true"
  WEBSERVER_PORT: "8080"
  RUN_MODE: "cron"
  IMMEDIATE_RUN: "true"
  CRON_SCHEDULE: "*/3 * * * *"
  WEWORK_WEBHOOK_URL: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=af5680a2-68b8-4d9e-92e3-57e1fe896536"
  WEWORK_MSG_TYPE: "markdown"

volumes:
  - name: trendradar-config-volume
    configMap:
      name: trendradar-config
      items:
        - key: config.prod.yaml
          path: config.yaml
        - key: frequency_words.txt
          path: frequency_words.txt
        - key: ai_analysis_prompt.txt
          path: ai_analysis_prompt.txt
        - key: ai_translation_prompt.txt
          path: ai_translation_prompt.txt
        - key: timeline.yaml
          path: timeline.yaml

# Additional volumeMounts on the output Deployment definition.
volumeMounts:
  - name: trendradar-config-volume # 与 volumes 中名称一致
    mountPath: /app/config # 容器内挂载路径
    readOnly: true # 可读写（配置文件可设为 true）
